### ISSUE TITLE
An imported csv may contain null values and not render on Step 2. 

### ISSUE THREAD

**Issue by garethcull** [garethcull/forecastr#2]
Sometimes a dataset may contain a null value or contain multiple columns defined as objects.

Example:
I imported some data from the [Time Series Data Library](https://datamarket.com/data/list/?q=provider%3Atsdl), and one of the rows contain a '?'. This question mark is actually indicative of a negative value and the entire column then get's classified with dtype = object.

Need to create some error messaging around this error and emit this back to the client side so that the user can take a look at the row in question.

**Comment by garethcull** [comment]
Going to close this and re-open a new issue to review the data types of each column imported.

**Comment by gofornaman** [comment]
Hi @garethcull, I'm facing the same CSV null issue. Unable to import external dataset. Did you happen to solve this problem, can you guide me as well? Thanks!
