### ISSUE TITLE
compare past actuals to future forecast

### ISSUE THREAD

**Issue by huntermaxfield** [garethcull/forecastr#5]
It would be great to be able to see how the forecast compares to the past for the same time interval that was predicted.  This would allow users to see how they are tracking towards their KPI's.

**Comment by garethcull** [comment]
Thanks @huntermaxfield. I pushed this code and was wondering if you want to check it out? We now have forecast comparisons vs. the previous period.

https://github.com/garethcull/forecastr/commit/05670f301c31ffba40cba77a911b3efdb2121624

**Comment by garethcull** [comment]
@huntermaxfield Check it out. I just pushed your changes to production. It looks like it is working well :) This is so awesome. Thanks Hunter!!!

https://forecastr-io.herokuapp.com/app/
